[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = GNYPJG5HCz4WKc6xZhPe0bD/CXylrb3rVe4RJtCgsHo=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#21
PublicKey = e5uXqSk+KIt3G4dAlbY+9hPvK//zyxQTwdNRS5vLbmc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.216.221.75:51820

PersistentKeepalive = 25