[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = iCTMNIY+G9Uixi26WPky5PNuoLg9pf2VLrQAht2hR30=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#13
PublicKey = 2WRemi/oNhZ3NJ4ItTm6lGIbo91ATLtWtTNb1SsC21I=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.216.221.67:51820

PersistentKeepalive = 25