[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = eOTBs0wtI/3154cMGz1xdTgFSA4lXrldV6nQlRuzFmU=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#9
PublicKey = dhtz5+jUyF+37NmZc2WIEOTf7/UTJlaT1ojEGkPMPiI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.23.107:51820

PersistentKeepalive = 25