[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = sDt+wjmOtkuHrW6xceovu04HupKiDMSxyR8FcLZ/o0g=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#26
PublicKey = u8TqDmhDMeQcMJbMbi8uRcFfXEm5RdOGHygvuEesV0Y=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.40.62.56:51820

PersistentKeepalive = 25